vars_life <- c("country",
               "commun",
               "surveypl",
               "surveyyr", 
               "hhnum",
               "year", 
               "sex", 
               "age",
               "educ",
               "statebrn",
               "cunion",
               "married",
               "children",
               "occup",
               "land",
               "property",
               "business",
               "abyr1",
               "abstate1",
               "abstatel",
               "abyrl",
               "abdur",
               "abtrips",
               "abborn",
               "faabmig",
               "weight")

vars_spouse <- c("country",
                 "commun",
                 "surveypl",
                 "surveyyr",
                 "hhnum",
                 "year",
                 "lifeyr",
                 "age",
                 "sex",
                 "yrborn",
                 "educ",
                 "statebrn",
                 "occup",
                 "jchange",
                 "jobplace", 
                 "jobstate",
                 "abroad",
                 "trip",
                 "tripnum",
                 "abdur",
                 "abcumexp",
                 "abborn",
                 "abyr1",
                 "abstate1",
                 "abmar1",
                 "abocc1",
                 "abstatel",
                 "abyrl",
                 "abtrips",
                 "abdur",
                 "abexp",
                 "weight")

vars_spouse_min <- c("country",
                     "commun",
                     "surveypl",
                     "surveyyr",
                     "hhnum",
                     "year",
                     "sex",
                     "abstate1",
                     "abstatel",
                     "statebrn",
                     "abyr1",
                     "abyrl",
                     "abdur",
                     "abtrips",
                     "weight")

vars_hh <- c("country", "surveyyr", "surveypl", "commun", "hhnum")


# vars_lampABM ------------------------------------------------------------

# Vars used in the model.
  # Dummy commun and ocstat need to be added separately.
vars_lampABM <- c("lgg_educ",
                  "lgg_partner",
                  "lgg_children",
                  "lgg_ocstat_Unskilled_manual",
                  "lgg_ocstat_Skilled_manual",
                  "lgg_ocstat_Lower_service",
                  "lgg_ocstat_Routine_non_manual",
                  "lgg_ocstat_Salariat",
                  "lgg_ocstat_Unemployed",
                  "lgg_wexp_lg",
                  "lgg_duasset",
                  "lgg_mnet_intra",
                  "lgg_mnet_usa",
                  "lgg_mnet_spain",
                  "lgg_mnet_international_commun")

# Time variant variables. To be lagged.
vars_tv <- c("educ",
            "partner",
            "children",
            "ocstat_Unskilled_manual",
            "ocstat_Skilled_manual",
            "ocstat_Lower_service",
            "ocstat_Routine_non_manual",
            "ocstat_Salariat",
            "ocstat_Unemployed",
            "employed",
            "wexp",
            "wexp_lg",
            "duasset",
            "mnet_intra",
            "mnet_usa",
            "mnet_spain",
            "mnet_international_commun")

# Vars macro --------------------------------------------------------------

vars_macro <- c("border_840",
                "border_724",
                "violence",
                "gdp",
                "egrowth_usa",
                "egrowth_spain",
                "oilpr")


# Vars sample descriptives ------------------------------------------------

# Variables of interest.
vars_sample_desc <- c("event_international", 
                      "event_intra",
                      "event_usa",
                      "event_spain",
                      "age",
                      "female",
                      "educ",
                      "partner",
                      "children",
                      "ocstat_Unskilled_manual",
                      "ocstat_Skilled_manual",
                      "ocstat_Lower_service",
                      "ocstat_Routine_non_manual",
                      "ocstat_Salariat",
                      "ocstat_Unemployed",
                      "wexp",
                      "duasset",
                      "mnet_intra",
                      "mnet_usa",
                      "mnet_spain",
                      "mnet_international_commun",
                      "commun_1",
                      "commun_2",
                      "commun_3",
                      "commun_4",
                      "commun_5",
                      "commun_6",
                      "commun_7",
                      "commun_8",
                      "commun_9",
                      "commun_10",
                      "commun_11",
                      "commun_12",
                      "commun_13",
                      "commun_14",
                      "border_840",
                      "border_724",
                      "violence",
                      "gdp",
                      "egrowth_usa",
                      "egrowth_spain",
                      "oilpr")


